root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
pre_cmd = []
cmd = "go build -C ./cmd/swaystats -o  ../../tmp/swaystats"
post_cmd = []
bin = "tmp/swaystats"
include_ext = ["go"]
exclude_dir = ["tmp"]
include_dir = []
include_file = []
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
poll = false
poll_interval = 500
delay = 0
stop_on_error = true
send_interrupt = false
kill_delay = 500
rerun = false
rerun_delay = 500

[log]
time = false
main_only = false
silent = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true

[proxy]
enabled = false
proxy_port = 8090
app_port = 8080
